version: '3.7'
services:
    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: admin12345
            MYSQL_DATABASE: chat_sys_dev
        ports:
            - "3307:3306"
        tty: true
    app: 
        build: .
        command: bash -c "bash ./init.sh && bundle exec rails s -p 3000 -b '0.0.0.0'"
        tty: true
        volumes: 
            - ".:/app"
        ports: 
            - "3001:3000"
        depends_on:
            - db
        links:
            - db:mysql
        environment:
            DB_USER: root
            DB_NAME: chat_sys_dev
            DB_PASSWORD: admin12345
            DB_HOST: db