version: '3.7'
services:
    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:8.2.2
      container_name: elasticsearch
      restart: always
      environment:
        - xpack.security.enabled=false
        - discovery.type=single-node
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - elasticsearch-data-volume:/usr/share/elasticsearch/data
      ports:
        - 9200:9200

    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: admin12345
            MYSQL_DATABASE: chat_sys_dev
        ports:
            - "3307:3306"
        tty: true

    redis:
      image: 'redis:5-alpine'
      command: redis-server
      ports:
        - '6379:6379'
      volumes:
        - 'redis:/data'

    app: 
        build: .
        command: bash -c "bash ./init.sh && bundle exec rails s -p 3000 -b '0.0.0.0'"
        tty: true
        volumes: 
            - ".:/app"
        ports: 
            - "3001:3000"
        depends_on:
            - elasticsearch
            - db
            - redis
        links:
            - elasticsearch
            - db:mysql
            - redis
        environment:
            - ES_HOST=elasticsearch
            - DB_USER=root
            - DB_NAME=chat_sys_dev
            - DB_PASSWORD=admin12345
            - DB_HOST=db

volumes: 
  elasticsearch-data-volume:
    driver: local
  redis:
  db: